### ISSUE TITLE
Detalhes

### ISSUE THREAD

**Issue by gmasson** [happyto/amcra-site#1]
Obrigado por criar o repositório @dudemelo 
Eu ainda não oficializei essa regra, mas dentro dos repositórios vamos criar branches "model-x" , cujo todos os modelos vamos disponibilizar separados por branches, por isso que criei a branch "model-1" .. ai conforme você e o restante for criando, colocaremos dentro dessa branch.

E você fez exatamente do jeito que eu estava planejando, colocar o nome do repositório "nomedaong-site" ... shoow de bola!

**Comment by dudemelo** [comment]
De nada @gmasson !

Criei o repositório para que possamos preparar a estrutura inicial do tema, enquanto o layout ainda não está aprovado.

Sobre a nomenclatura dos branches, o que seria "modelo"?

**Comment by gmasson** [comment]
Modelo vai ser o modelo que usaremos, por exemplo, faremos a primeira versão agora (model-1) .. digamos que daqui 2 anos o pessoal do AMCRA entre em contato pedindo um novo site, não precisaremos criar um novo repositório, usaremos as branches para trabalhar e manter todos os layouts desenvolvidos no ar.
